export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_RANDOM_ENTRIES = 'SET_RANDOM_ENTRIES';
export const ADD_RANDOM_ENTRIES = 'ADD_RANDOM_ENTRIES';
export const SET_ENTRY_ENTRIES = 'SET_ENTRY_ENTRIES';
export const ADD_ENTRY_ENTRIES = 'ADD_ENTRY_ENTRIES';

export const SET_HAS_LOADED_ENTRIES = 'SET_HAS_LOADED_ENTRIES';
